# netlify.toml
[build]
  base = "one-piece-manager"
  publish = "dist"  # ✅ CORRIGIDO: apenas "dist" pois já está no base
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"  # ✅ ATUALIZADO para Node 20

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://pagead2.googlesyndication.com https://googleads.g.doubleclick.net; frame-src https://googleads.g.doubleclick.net; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200